<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Authors>Vladyslav Zaiets</Authors>
    <PackageProjectUrl>https://github.com/sarmkadan/dotnet-deploy-notify</PackageProjectUrl>
  </PropertyGroup>
</Project>